package models

import (
	"time"
)

type SceneMarker struct {
	ID           int       `json:"id"`
	Title        string    `json:"title"`
	Seconds      float64   `json:"seconds"`
	EndSeconds   *float64  `json:"end_seconds"`
	Rating100    *int      `json:"rating100"`
	PrimaryTagID int       `json:"primary_tag_id"`
	SceneID      int       `json:"scene_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`

	// AutoGenerated is true if this marker was created automatically (e.g.
	// by ffmpeg-based scene-cut detection) rather than by a user.
	AutoGenerated bool `json:"auto_generated"`
}

func NewSceneMarker() SceneMarker {
	currentTime := time.Now()
	return SceneMarker{
		CreatedAt: currentTime,
		UpdatedAt: currentTime,
	}
}

// SceneMarkerPartial represents part of a SceneMarker object.
// It is used to update the database entry.
type SceneMarkerPartial struct {
	Title         OptionalString
	Seconds       OptionalFloat64
	EndSeconds    OptionalFloat64
	Rating100     OptionalInt
	PrimaryTagID  OptionalInt
	TagIDs        *UpdateIDs
	SceneID       OptionalInt
	CreatedAt     OptionalTime
	UpdatedAt     OptionalTime
	AutoGenerated OptionalBool
}

func NewSceneMarkerPartial() SceneMarkerPartial {
	currentTime := time.Now()
	return SceneMarkerPartial{
		UpdatedAt: NewOptionalTime(currentTime),
	}
}
