// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// PlaylistReaderWriter is an autogenerated mock type for the PlaylistReaderWriter type
type PlaylistReaderWriter struct {
	mock.Mock
}

// AddScene provides a mock function with given fields: ctx, playlistID, sceneID
func (_m *PlaylistReaderWriter) AddScene(ctx context.Context, playlistID int, sceneID int) error {
	ret := _m.Called(ctx, playlistID, sceneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, playlistID, sceneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddScenes provides a mock function with given fields: ctx, playlistID, sceneIDs
func (_m *PlaylistReaderWriter) AddScenes(ctx context.Context, playlistID int, sceneIDs []int) error {
	ret := _m.Called(ctx, playlistID, sceneIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, playlistID, sceneIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// All provides a mock function with given fields: ctx
func (_m *PlaylistReaderWriter) All(ctx context.Context) ([]*models.Playlist, error) {
	ret := _m.Called(ctx)

	var r0 []*models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Playlist); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearScenes provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistReaderWriter) ClearScenes(ctx context.Context, playlistID int) error {
	ret := _m.Called(ctx, playlistID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, newPlaylist
func (_m *PlaylistReaderWriter) Create(ctx context.Context, newPlaylist *models.Playlist) error {
	ret := _m.Called(ctx, newPlaylist)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Playlist) error); ok {
		r0 = rf(ctx, newPlaylist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *PlaylistReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *PlaylistReaderWriter) Find(ctx context.Context, id int) (*models.Playlist, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Playlist); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *PlaylistReaderWriter) FindByName(ctx context.Context, name string) (*models.Playlist, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Playlist); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDefault provides a mock function with given fields: ctx
func (_m *PlaylistReaderWriter) FindDefault(ctx context.Context) (*models.Playlist, error) {
	ret := _m.Called(ctx)

	var r0 *models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context) *models.Playlist); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids
func (_m *PlaylistReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Playlist, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.Playlist); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlaylistsWithScene provides a mock function with given fields: ctx, sceneID
func (_m *PlaylistReaderWriter) GetPlaylistsWithScene(ctx context.Context, sceneID int) ([]*models.Playlist, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 []*models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Playlist); ok {
		r0 = rf(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSceneIDs provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistReaderWriter) GetSceneIDs(ctx context.Context, playlistID int) ([]int, error) {
	ret := _m.Called(ctx, playlistID)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSceneInPlaylist provides a mock function with given fields: ctx, playlistID, sceneID
func (_m *PlaylistReaderWriter) IsSceneInPlaylist(ctx context.Context, playlistID int, sceneID int) (bool, error) {
	ret := _m.Called(ctx, playlistID, sceneID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, playlistID, sceneID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, playlistID, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, playlistFilter, findFilter
func (_m *PlaylistReaderWriter) Query(ctx context.Context, playlistFilter *models.PlaylistFilterType, findFilter *models.FindFilterType) ([]*models.Playlist, int, error) {
	ret := _m.Called(ctx, playlistFilter, findFilter)

	var r0 []*models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, *models.PlaylistFilterType, *models.FindFilterType) []*models.Playlist); ok {
		r0 = rf(ctx, playlistFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Playlist)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *models.PlaylistFilterType, *models.FindFilterType) int); ok {
		r1 = rf(ctx, playlistFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *models.PlaylistFilterType, *models.FindFilterType) error); ok {
		r2 = rf(ctx, playlistFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveScene provides a mock function with given fields: ctx, playlistID, sceneID
func (_m *PlaylistReaderWriter) RemoveScene(ctx context.Context, playlistID int, sceneID int) error {
	ret := _m.Called(ctx, playlistID, sceneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, playlistID, sceneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReorderScene provides a mock function with given fields: ctx, playlistID, sceneID, position
func (_m *PlaylistReaderWriter) ReorderScene(ctx context.Context, playlistID int, sceneID int, position int) error {
	ret := _m.Called(ctx, playlistID, sceneID, position)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, playlistID, sceneID, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SceneCount provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistReaderWriter) SceneCount(ctx context.Context, playlistID int) (int, error) {
	ret := _m.Called(ctx, playlistID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDefault provides a mock function with given fields: ctx, id
func (_m *PlaylistReaderWriter) SetDefault(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, partial
func (_m *PlaylistReaderWriter) Update(ctx context.Context, id int, partial models.PlaylistPartial) (*models.Playlist, error) {
	ret := _m.Called(ctx, id, partial)

	var r0 *models.Playlist
	if rf, ok := ret.Get(0).(func(context.Context, int, models.PlaylistPartial) *models.Playlist); ok {
		r0 = rf(ctx, id, partial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.PlaylistPartial) error); ok {
		r1 = rf(ctx, id, partial)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
